# Generated by Django 2.1.5 on 2019-02-11 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='compte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('prenom', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('addresse', models.TextField()),
                ('ville', models.CharField(max_length=255)),
                ('code_postale', models.CharField(max_length=255)),
                ('sexe', models.CharField(max_length=8)),
                ('date', models.DateField()),
                ('statut', models.CharField(max_length=255)),
            ],
        ),
    ]
